language: python
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=hg35
    - TOXENV=hg36
    - TOXENV=coverage
install: pip install docutils tox
script: tox
